# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
