# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_accounts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='male', max_length=10),
        ),
    ]
