# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_accounts_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
