# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_accounts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='image',
            field=models.ImageField(editable=False, height_field=100, null=True, upload_to='polls/image/', width_field=100),
        ),
    ]
