# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180815_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_img'),
        ),
    ]
