# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180815_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='image',
        ),
    ]
