# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_accounts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(choices=[('Science', 'Science'), ('Arts', 'Arts')], max_length=15, null=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Accounts')),
            ],
        ),
    ]
