# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
